name: favelasemcorona
description: Ajudando a diminuir o impacto do virus nas comunidades

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.11
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  cloud_firestore: ^0.13.4+2
  webview_flutter: ^0.3.19+9
  url_launcher: ^5.4.2
  dio: ^3.0.9
  firebase_core: ^0.4.4+3
  shared_preferences: ^0.5.7
  flutter_spinkit: "^4.1.2"



dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

flutter:
  uses-material-design: true

  assets:
  - images/
